// ============================================
// Analytics Library Exports
// ============================================

export {
  initGA,
  pageview,
  pageviewSPA,
  event,
  trackClick,
  trackFormSubmit,
  setUserProperties,
  setUserId,
  updateConsent,
  defaultConsent,
  viewItem,
  viewItemList,
  selectItem,
  addToCart,
  removeFromCart,
  viewCart,
  beginCheckout,
  addShippingInfo,
  addPaymentInfo,
  purchase,
  search,
  scroll,
  videoStart,
  videoComplete,
  setCustomDimension,
  setCustomMetric,
} from './gtag'

export {
  productToAnalyticsItem,
  cartItemToAnalyticsItem,
  trackProductView,
  trackProductListView,
  trackProductSelect,
  trackAddToCart,
  trackRemoveFromCart,
  trackViewCart,
  trackBeginCheckout,
  trackAddShippingInfo,
  trackAddPaymentInfo,
  trackPurchase,
  trackSearch,
  trackCTAClick,
  trackNavigation,
  trackProjectView,
  trackContactSubmit,
  trackDownload,
  trackSocialShare,
  trackVideoPlay,
  trackScrollDepth,
  trackTimeOnPage,
  trackError,
  trackPageLoad,
  trackWebVitals,
  setUserLocalePreference,
  setUserType,
} from './events'
